config/routes.rb
Rails.application.routes.draw do
  
  root 'landings#index'

  resources :drills

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/drill.rb
class Drill < ActiveRecord::Base
  has_many :paced_drills
  has_many :practices, through: :paced_drills
end

app/models/paced_drill.rb
class PacedDrill < ActiveRecord::Base
  belongs_to :practice
  belongs_to :drill
end

app/models/practice.rb
class Practice < ActiveRecord::Base
  has_many :scheduled_practices
  has_many :paced_drills
  has_many :drills, through: :paced_drills
end

app/models/scheduled_practice.rb
class ScheduledPractice < ActiveRecord::Base
  belongs_to :practice
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drills_controller.rb
class DrillsController < ApplicationController

	def index
		@drills = Drill.all
	end

	def new
		@drill = Drill.new
	end

	def create
		@drill = Drill.new(drill_params)

    	respond_to do |format|
      		if @drill.save
        		format.html { redirect_to @drill, notice: 'Drill was successfully created.' }
        		format.json { render :show, status: :created, location: @drill }
      		else
        		format.html { render :new }
        		format.json { render json: @drill.errors, status: :unprocessable_entity }
      		end
    	end
	end

	def show
		@drill = Drill.find(params[:id])
	end

	private

		def drill_params
			 params.require(:drill).permit(:name, :distance, :unit, :description)
		end

end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
	
	def index

	end

end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController

	def index
		@practices = Practice.all
	end

	def new
		@practice = Practice.new
	end

	def create
		@practice = Practice.new(practice_params)

    	respond_to do |format|
      		if @practice.save
        		format.html { redirect_to @practice, notice: 'Group was successfully created.' }
        		format.json { render :show, status: :created, location: @practice }
      		else
        		format.html { render :new }
        		format.json { render json: @practice.errors, status: :unprocessable_entity }
      		end
    	end
	end

	def show
		@practice = Practice.find(params[:id])
	end

	private

		def practice_params
			 params.require(:practice).permit(:author, :duration, :notes)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drills_helper.rb
module DrillsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/views/drills/_form.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Drill %></h1>
</div>

<%= form_for @drill, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-3">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :distance, :class => 'control-label col-md-2' %>
    <div class="col-md-3">
      <%= f.text_field :distance, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :unit, :class => 'control-label col-md-2' %>
    <div class="col-md-3">
      <%= f.text_field :unit, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-3">
      <%= f.text_field :description, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  drills_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/drills/index.html.erb
<% @drills.each do |d| %>
	<%= link_to d.name, drill_path(d) %>
	<%= d.distance %>
	<%= d.unit %>
	</br>
<% end %>

<%= link_to "new", new_drill_path %>

app/views/drills/new.html.erb
<%- model_class = Drill -%>
<%= render 'form' %>

<%= link_to "index",  drills_path %>

app/views/drills/show.html.erb
<%= @drill.name %>
<%= @drill.distance %>
<%= @drill.unit %>
<%= @drill.description %>
</br>
<%= link_to "new", new_drill_path%>
</br>
<%= link_to "index",  drills_path %>

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/landings/index.html.erb
Sample text


<%= link_to "drills",  drills_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Setgenmodule</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>

app/views/practices/new.html.erb
<%- model_class = Practice -%>

<%= form_for @Practice, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :author, :class => 'control-label col-md-2' %>
    <div class="col-md-3">
      <%= f.text_field :author, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :notes, :class => 'control-label col-md-2' %>
    <div class="col-md-3">
      <%= f.text_field :notes, :class => 'text-field form-control' %>
    </div>
  </div>
<% end %>


<%= link_to "index",  practices_path %>